###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://sap.github.io/jenkins-library/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  inferBuildTool: true
  unsafeMode: false
  projectName: 'cloud-extension-s4hana-business-process'
  productiveBranch: 'main'

### Step-specific configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag
    buildTool: 'mta'
  npmExecute:
    dockerImage: 'ppiper/node-browsers:v2'
  cloudFoundryDeploy:
    dockerImage: 'ppiper/cf-cli'
    mtaDeployParameters: '-f --version-rule ALL'
  mtaBuild:
    mtaBuildTool: "cloudMbt"

### Stage-specific configuration
stages:
  'Confirm':
    manualConfirmation: false

  npmAudit:
    auditedAdvisories:
    # high
      - 550   
      - 593
      - 1184
      - 755
      - 1065 
      - 1164 
      - 1316 
      - 1324 
      - 1325 
    # moderate
      - 535
      - 1300 

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

Release:
     cfTargets:
       - org: 'CoCo-Demo_GeoRel'
         space: 'dev'
         apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
         appName: 'myAppName'
         manifest: 'manifest.yml'
         credentialsId: 'myDeploymentCredentialsId'
